language: go
go:
        - tip
script: go get golang.org/x/tools/cmd/vet && go get github.com/lziest/goZKP && go test github.com/lziest/goZKP/... && go vet github.com/lziest/goZKP/...
notifications:
        email:
                recipients:
                        - zi.lin.cs@gmail.com
                on_success: never
                on_failure: change
